server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      # Global defaults applied to all discovery-client traffic if enabled
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path = /api/v1/auth/**
            - Method = GET,POST
          filters:
            - StripPrefix = 2

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path = /api/v1/customer/**
            - Method = GET, POST, PUT, DELETE
          filters:
            - StripPrefix = 2

